version: '3.8'
name: 'webdev'

services:
  elysia:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: elysia
    ports:
      - "${ELYISIA_PORT:-3000}:3000"
    environment:
      - NODE_ENV=development
      - BUN_ENV=development
    volumes:
      - ./backend:/app
      - /app/node_modules
    restart: unless-stopped


  vite:
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: vite
    ports:
      - "${REACT_PORT:-3001}:5173"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - BUN_ENV=${NODE_ENV:-development}
      - VITE_BACKEND_URL=${BACKEND_URL:-http://185.179.190.134:3000/}
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: unless-stopped

